### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by david-dickinson** [samhudis/RunMyMap#2]
- [x] Match formatting of sample wiki for the schema
- [x] Include a `polyline` `string` in your `Runs` table - this will be how you store the data necessary for Google Maps.
- [x] Think about including another column in your `Friends` table indicating whether the friendship has been accepted or not - otherwise, all friending is automatically approved.
- [x] No need to have a `Maps` table - all the information there can be stored as a polyline in the `Runs` table

**Comment by samhudis** [comment]
Made appropriate changes to schema doc
